spring:
  application:
    name: modular-rag
  ai:
    mistralai:
      api-key: "${MISTRALAI_API_KEY:fake}"
      chat:
        base-url: http://localhost:11434
        options:
          model: mistral
      embedding:
        base-url: http://localhost:11434
        options:
          model: nomic-embed-text
